### ISSUE TITLE
Questions.

### ISSUE THREAD

**Issue by Dairon-Juraski** [develFoss/dotfiles#1]
Hey man, I hope you can help me with some insues. sorry for the contact here, but your post on reddit has been removed. Like this:
1 - How do you put icons in your settings, because I can't even see them;
2 - Is there a specific package to view Unicode in Arch ??
3 - Is there a right method to install fonts, so that I can use your icons?

Thanks in advance.
Juraski

**Comment by folliehiyuki** [comment]
This repos is not maintained anymore (coz I lost its credential info), please refer to my new account for future stuff. Sorry for the late reply though.
As for your questions:
1 - By typing them directly (Ctrl + Shift + u in most terminal emulators if they support it) or something like this "\uf794" (f794 here is the Unicode code). For your machine to recognize those symbols correctly you need specify fonts (which fit your need). Install an emoji fonts if you want color icons or Awesome fonts/Nerd fonts for glyph icons.
2 - I don't use any so I can't tell. For Nerd fonts and Awesome fonts you can check the cheat sheets on their websites. I remember Gnome has its gnome-font-viewer package, but it doesn't play nice with those glyph characters. I use ibus for emoji finding and insertion.
3 - Download the font files directly into ~/.local/share/fonts/ or install it from the package repos of your distro? Which is right depends on you though.

**Comment by Dairon-Juraski** [comment]
Tks
